version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
before_build:
  - git submodule update --init --recursive
build_script:
  - .\build.release.bat
test_script:
  - dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration Release --no-build --framework netcoreapp2.1
  - dotnet test Tests/CSharpCore/Tests.NetStandard.csproj --configuration Release --no-build --framework net452
